[package]
id = "xjoy27d3i4hc4l7fmlm5pacc2cmxlnlw"
name = "Dependencies"
description = "Break your project up into packages."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[dependencies]
deps_assets = { path = "deps/assets" , deployment = "5Nh8HFyEtbxsogtNGxGkkq" }
deps_code = { path = "deps/code" , deployment = "38BojIxrmzw0qm5tj0eoCQ" }
orbit_camera = { path = "../../../packages/std/orbit_camera" , deployment = "66hEWoZwDe3zJ9kEYGWeH8" }
