[package]
id = "t33j53muycmj4i66en5lheneowad5hbz"
name = "Dependencies (Code)"
version = "0.0.1"
content = { type = "Asset", code = true }

[dependencies]
ambient_example_deps_assets = { path = "../assets" , deployment = "5Nh8HFyEtbxsogtNGxGkkq" }

[components]
spawned_by_us = { type = "Empty" }
spin_direction = { type = "ambient_example_deps_assets::SpinDirection" }

[messages.Spawn]
name = "Spawn"
description = "Spawn the asset."
[messages.Spawn.fields]
spin_speed = "F32"
spin_direction = "ambient_example_deps_assets::SpinDirection"
