[package]
id = "t5qdqwpkoxtelvafs7qpvzhaoperwfpt"
name = "Tangent"
description = "Ambient's tech demo game. Third-person, hovercars, and more."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Playable" }
ambient_version = "0.3.2-nightly-2023-11-27"
authors = ["philpax"]

[dependencies]
hide_cursor = { path = "../../std/hide_cursor", deployment = "5rKGYgK4g17FfZrTlm8Ls1", enabled = true }

core = { path = "core/core", deployment = "1oXiLu4TpaPv2qOyrH2qnK" }
behavior_vehicle = { path = "core/behavior_vehicle", deployment = "4HeOmVa0k5tdPZVWFOtmXi" }
behavior_character = { path = "core/behavior_character", deployment = "18lpBpbn9sqU63ntGE32c1" }
camera_follow = { path = "core/camera_follow", deployment = "1AdB8KnrcDvxtpkaK6DFcg" }
ui_class_selection = { path = "core/ui_class_selection", deployment = "20AHpCAkXHgU2n9LAdLXOM" }

camera_topdown = { path = "mods/camera_topdown", enabled = false, deployment = "1muEZDfzxssgDly0aMTxzD" }

ui_holohud = { path = "mods/ui_holohud", enabled = false, deployment = "PZmQSNYzZgFDoqUBFrhHT" }
ui_flathud = { path = "mods/ui_flathud", enabled = true, deployment = "2fORIYQ1ShgaMk7hroAqLS" }
ui_spawn_menu = { path = "mods/ui_spawn_menu", enabled = false, deployment = "4xvw35UlYJpXKRqpmKhVcr" }

pickup_health = { path = "mods/pickup_health", deployment = "JoqF8dZO0KJ94i8J1BFJp" }

level_cubicide = { path = "mods/level_cubicide", deployment = "1S6kupF80XA5RV85hVef74" }
level_cubicide_onespawn = { path = "mods/level_cubicide_onespawn", enabled = false, deployment = "6OTzqKFtM0Fh3yQjoSSHC6" }

class_assault = { path = "mods/class_assault", deployment = "5hIrZBUpSxj5bfbMSjNjUq" }
class_scout = { path = "mods/class_scout", deployment = "Ychj5xZ3UuE7YqpGseGTo", enabled = false }
class_tank = { path = "mods/class_tank", deployment = "qEG9G12BUip2zu5paXd1P" }

vehicle_standard = { path = "mods/vehicle_standard", deployment = "4uXRBWgVITVUYGqG4vKhNr" }

gameplay_firerain = { path = "mods/gameplay_firerain", enabled = false, deployment = "6xcIWItYgv8Zbkm6sEHWRO" }
gameplay_daynight = { path = "mods/gameplay_daynight", enabled = false, deployment = "oMul6FRRf9hzAZgZuWHy0" }

reskin_classes = { path = "mods/reskin_classes", enabled = false, deployment = "7ifYBWRFMMAqcJOANsv5LT" }

package_manager = { path = "../../tools/package_manager", deployment = "5ccSwEAHzOh16fpDArUQhs" }
editor = { path = "../../tools/editor", deployment = "1doeXcd8pDCKpSVmwipgi8" }
