[package]
id = "jkfalriqol5mtd7hxq7yssldubgpcf5o"
name = "animations"
version = "0.3.2-nightly-2023-11-27"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[dependencies]
base_assets = { path = "../../../packages/std/base_assets", deployment = "5aigIp1X7oiCRDZjGr1FSQ" }
character_animation = { path = "../../../packages/std/character_animation", deployment = "6jwKRIF1AlXd5z3S1vVQNA" }
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "66hEWoZwDe3zJ9kEYGWeH8" }
performance_bar = { path = "../../../packages/tools/performance_bar", deployment = "6DjX9N6zdytkk8HY95Dj7m" }
