[package]
id = "itzh3wovmdje4ttrmo6wrravaaxp6b52"
name = "Tangent Core"
description = "The core of Tangent. The connective glue between all the other packages. (Will likely be split up.)"
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", code = true }
authors = ["philpax"]
ambient_version = "0.3.2-nightly-2023-11-27"

[dependencies]
tangent_schema = { path = "../../schema", deployment = "27TaITYdVZ3fZg6wtrmkjT" }

game_object = { path = "../../../../schemas/game_object", deployment = "36xUYdd9Svl4bemFEF64Lv" }
unit_schema = { path = "../../../../schemas/unit", deployment = "mRHphHcpcpbNIvyHKUWaI" }

explosion = { path = "../../../../std/explosion", deployment = "2ByIELPdFD4BtCNy84hekC" }
nameplates = { path = "../../../../std/nameplates", deployment = "21rfbOAZo6BiNi7unRmgfN" }

kenney_impact_sounds = { path = "../../../../assets/kenney_impact_sounds", deployment = "24RSCc5u7oU4V0SEGR9YAs" }

[messages.Input]
name = "Input"
description = "Input"
[messages.Input.fields]
direction = "Vec2"
jump = "Bool"
fire = "Bool"
use_button = "Bool"
sprint = "Bool"
respawn = "Bool"
aim_direction = "Vec2"
# Let's not trust the client in the future
aim_ray_origin = "Vec3"
aim_ray_direction = "Vec3"

[messages.UseFailed]
name = "Use Failed"
description = "Sent from the server to the client when a use action fails."
fields = {}
