[package]
id = "ie4hdvkvui6t36yzniyex2hc5i2bradc"
name = "Third-person camera"
description = "A simple third-person camera controller."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/third_person_camera"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[dependencies]
base_assets = { path = "../../../packages/std/base_assets", deployment = "5aigIp1X7oiCRDZjGr1FSQ" }
third_person_controller = { path = "../../../packages/std/third_person_controller", deployment = "40M51JAR7eFTHkFImkfEAE" }
character_animation = { path = "../../../packages/std/character_animation", deployment = "6jwKRIF1AlXd5z3S1vVQNA" }
hide_cursor = { path = "../../../packages/std/hide_cursor", deployment = "5rKGYgK4g17FfZrTlm8Ls1" }
nameplates = { path = "../../../packages/std/nameplates", deployment = "21rfbOAZo6BiNi7unRmgfN" }
